# Generated by Django 4.2.15 on 2026-09-03 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Primary email address used for authentication.', max_length=255, unique=True)),
                ('first_name', models.CharField(help_text="User's first name.", max_length=150)),
                ('last_name', models.CharField(help_text="User's last name.", max_length=150)),
                ('phone', models.CharField(blank=True, default='', help_text='Optional phone number.', max_length=20)),
                ('profile_image', models.ImageField(blank=True, help_text='Optional profile image.', null=True, upload_to='profile_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the account was last updated.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['created_at'], name='idx_user_created'), models.Index(fields=['is_active'], name='idx_user_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
    ]
