# Generated by Django 4.2.30 on 2026-09-03 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document.', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card_statement', 'Credit Card Statement'), ('vendor_sales_bill', 'Vendor/Sales Bill'), ('check', 'Check')], help_text='The type of financial document.', max_length=30)),
                ('date_format', models.CharField(blank=True, choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY'), ('YYYY/MM/DD', 'YYYY/MM/DD')], default='', help_text='Optional date format hint for the parser.', max_length=20)),
                ('pdf_password', models.CharField(blank=True, default='', help_text='Optional password for encrypted PDF files.', max_length=255)),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file.', max_length=500)),
                ('file', models.FileField(help_text='The uploaded document file.', upload_to='documents/')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('png', 'PNG')], help_text='File extension/type.', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', help_text='Current processing status.', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, help_text='Parsed/OCR data extracted from the document.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if processing failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the document was uploaded.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the document was last updated.')),
                ('user', models.ForeignKey(help_text='The user who uploaded this document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the transaction.', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Transaction date.')),
                ('description', models.CharField(help_text='Transaction description or memo.', max_length=500)),
                ('category', models.CharField(blank=True, default='', help_text='Transaction category (e.g., groceries, utilities).', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount.', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Whether this is a debit or credit.', max_length=10)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Check number or reference ID.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('document', models.ForeignKey(blank=True, help_text='The source document this transaction was extracted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='documents.document')),
                ('user', models.ForeignKey(help_text='The user who owns this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_txn_user'), models.Index(fields=['date'], name='idx_txn_date'), models.Index(fields=['transaction_type'], name='idx_txn_type'), models.Index(fields=['category'], name='idx_txn_category')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='idx_doc_user'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='idx_doc_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='idx_doc_type'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='idx_doc_created'),
        ),
    ]
